### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by NotSoMik** [chingh1123/djs-v14-handler#1]
since you released this template when there was the dev version of djs, is the template up to date and does it work with the stable version of djs?

**Comment by chingh1123** [comment]
> since you released this template when there was the dev version of djs, is the template up to date and does it work with the stable version of djs?

hmm, thanks for remind me for this template
I will check it.

**Comment by NotSoMik** [comment]
I Tested it and it worked, will you add other things?

**Comment by chingh1123** [comment]
> I Tested it and it worked, will you add other things?

Maybe not add other things anymore
