### ISSUE TITLE
default_member_permissions

### ISSUE THREAD

**Issue by NotSoMik** [chingh1123/djs-v14-handler#2]
Does the handler support the default_member_permissions?

**Comment by chingh1123** [comment]
I don't really understand what you mean :(
The default member permission is stand for server members permission or user permissions or other things?

**Comment by NotSoMik** [comment]
I'm talking about this https://discord.com/developers/docs/interactions/application-commands.
![Screenshot_20220805-201402_Samsung Internet](https://user-images.githubusercontent.com/74645196/183136994-1efec576-e0d9-46fd-9d7c-8852f7088858.jpg
)

**Comment by GioGio03** [comment]
Also in handler > index.js line 39 shouldnt be 
**[ApplicationCommandType.Message, ApplicationCommandType.User]** and also subcommand **ApplicationCommandOptionType.Subcommand**

**Comment by chingh1123** [comment]
> Also in handler > index.js line 39 shouldnt be **[ApplicationCommandType.Message, ApplicationCommandType.User]** and also subcommand **ApplicationCommandOptionType.Subcommand**

It is same with "MESSAGE" and "USER" btw @GioGio03

**Comment by chingh1123** [comment]
> I'm talking about this https://discord.com/developers/docs/interactions/application-commands. ![Screenshot_20220805-201402_Samsung Internet](https://user-images.githubusercontent.com/74645196/183136994-1efec576-e0d9-46fd-9d7c-8852f7088858.jpg)

I didn't write this into the handler, you can add it yourself. @NotSoMik

**Comment by NotSoMik** [comment]
Alright
